routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::middleware(['auth'])->namespace('Dashboard')->group(function () {
    Route::get('/', 'IndexController@index')->name('admin.index');
    Route::resource('news', 'NewsController');
    Route::resource('roles', 'RoleController');
    Route::resource('users', 'UserController')->except(['show']);
    Route::resource('deseases', 'DeseaseController');
    Route::resource('objects', 'ObjectController')->only(['index', 'create', 'edit', 'store', 'update', 'destroy']);
    Route::post('pagination_limit', 'ObjectController@changePaginationLimit');
    Route::resource('faqs', 'FaqController')->only(['index', 'edit', 'create', 'store', 'update', 'destroy']);
    Route::resource('tags', 'TagController')->only(['index', 'store', 'update', 'destroy']);
    Route::get('search{page?}', 'ObjectController@search');
    Route::resource('locations', 'LocationController');
    Route::resource('informations', 'InfoController');
    Route::resource('forms', 'CardsController');
    Route::resource('galleries', 'GalleryController');
});

app/Models/Info.php
<?php

namespace App\Models;

use App\Exceptions\FormException;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\ModelNotFoundException;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Validator;

class Info extends Model
{
    /**
     * @var array
     */
    public static $validation_message = [
        'required' => ':attribute is required',
        'email' => ':attribute is note email',
        'unique' => ':attribute already exist',
    ];
    /**
     * @var array
     */
    protected $fillable = [
        'user_id',
        'organisation_description',
        'stars',
        'payments_terms',
        'docs',
        'honour',
        'contraindications',
        'medical_profiles',
        'treatment_methods',
        'services',
    ];

    public function __construct(array $attributes = array())
    {
        parent::__construct($attributes);
    }

    /**
     * @param $data
     * @return array
     */
    public static function createOrUpdate(Request $request, $data)
    {
        $auth = Auth::user();
        $data = $data["infoform"];
        $nagradiArr = array();
        $data['user_id'] = Auth::id();
        $data['organisation_description'] = (string)$data["description"]["value"];
        $data['stars'] = (string)$data["stars"]["value"];
        $data['payments_terms'] = (string)$data["paymentconditions"]["value"];
        $data['docs'] = (string)$data["documentslist"]["value"];
        $data['contraindications'] = (string)$data["contraindications"]["value"];
        foreach ($data["honour"]["value"] as $val) {
            $img = $val["url"];
            $extension = explode(';', $img);
            $ini = str_replace("data:image/", "",$extension[0]);
            $img = str_replace('data:image/jpeg;base64,','',$img);
            $img = str_replace('data:image/jpg;base64,','',$img);
            $img = str_replace('data:image/png;base64,','',$img);
            $img = str_replace('data:image/bmp;base64,','',$img);
            $filename = $data['user_id']."_".rand(100, 99999999) . ".".$ini;
            if(Storage::disk('nagradi')->put($filename, base64_decode($img))){
                $nagradiArr[] = $filename;
            }
        }
        $data['honour'] = implode(",", $nagradiArr);
        $data['medical_profiles'] = isset($data["medprofile"]["value"][0]) ? implode("@,@", $data["medprofile"]["value"]) : "";
        $data['treatment_methods'] = isset($data["medmethods"]["value"][0]) ? implode("@,@", $data["medmethods"]["value"]) : "";
        $data['services'] = isset($data["solutions"]["value"][0]) ? implode("@,@", $data["solutions"]["value"]) : "";

//        if(!empty($data["honour"]["value"])){
//            $imgInfo = $data["honour"];
//            $imagesArr = $request->input('profileform.avatar.value');
//            foreach ($imagesArr as $img) {
//                $imgInfo = $img["url"];
//                $imgInfo = str_replace('data:image/jpeg;base64,','',$imgInfo);
//                $imgInfo = str_replace('data:image/jpg;base64,','',$imgInfo);
//                $imgInfo = str_replace('data:image/png;base64,','',$imgInfo);
//                $imgInfo = str_replace('data:image/bmp;base64,','',$imgInfo);
//                $img = explode(',', $imgInfo);
//                $ini = substr($img[0], 11);
//                $type = explode(';', $ini);
//                $filename = $user->id.rand(1000, 9999999999).'.'.$type;
//                if(Storage::disk('nagradi')->put($filename, base64_decode($imgInfo))){
//                    $data['honour'][] = $filename;
//                }
//            }
//            $data['honour'] = implode(",", $data['honour']);
//        }
//            $data['user_id'] = 1;
//        try{
//            $v = Validator::make($data, [
//                'organisation_description' => 'required',
//                'stars' => 'required',
//                'payments_terms' => 'required',
//                'docs' => 'required',
//                'contraindications' => 'required',
//                'medical_profiles' => 'required',
//                'treatment_methods' => 'required',
//                'services' => 'required',
//            ],self::$validation_message);

//            if ($v->fails()) {
//                $status = Response::HTTP_BAD_REQUEST;
//                $response = [
//                    'status' => $status,
//                    'message' => $v->errors(),
//                ];
//                throw new FormException($response);
//            }
//                return $response = [
//                        'status' => 200,
//                        'message' => $data,
//                    ];
            $info = Info::where("user_id", $data["user_id"])->first();

            if(empty($info)){
                Info::create($data);

                $status = Response::HTTP_OK;
                $response = [
                    'status' => $status,
                    'message' => 'Информация успешно сохранена.',
                ];
            }else{
                $data['info_id'] = $info->id;
                $infoObj = new Info();
                if($info->update($data)){
                    $response = [
                        'status' => Response::HTTP_OK,
                        'message' => 'Информация успешно обновлена.',
                    ];
                }
            }

            return $response;
//        }catch (\Exception $e){
//            $status = Response::HTTP_BAD_REQUEST;
//            $response = [
//                'status' => $status,
//                'message' => 'Что-то пошло не так.',
//            ];
//        }
//        return $response;
    }

    /**
     * @return array
     */
    public static function getInfo($id)
    {
        if(empty($id)){
            $auth = Auth::user();
            $news = Info::where('user_id', Auth::id())->first();
            if(empty($news)){
                $status = Response::HTTP_BAD_REQUEST;
                $response = [
                    'status' => $status,
                    'message' => 'Ничего не найдено.',
                ];
            }else{
                $i = 0;
                $news->original['description'] = $news->original["organisation_description"];
                $news->original['payments_terms'] = $news->original["paymentconditions"];
                $news->original['documentslist'] = $news->original["docs"];
                $news->original['medprofile'] = $news->original["medical_profiles"];
                $news->original['medmethods'] = $news->original["treatment_methods"];
                $news->original['solutions'] = $news->original["services"];
                foreach ($news->original as $k => $item) {
                    $moderate = 0;
                    if($k == "status"){
                        if($item == "accept"){
                            $moderated = "true";
                        }elseif($item == "declined"){
                            $moderated = "false";
                        }
                    }
                    if($k == "honour"){
                        $info[$k]["name"] = $k;
                        $info[$k]["type"] = "file";
                        $info[$k]["value"][$i]["url"] = !empty($item) ? "/profiles/nagradi/".$item : "";
                        $info[$k]["value"][$i]["uid"] = rand(100, 999999);
                        $info[$k]["value"][$i]["size"] = !empty($item) ? filesize("/var/www/client/static/profiles/nagradi/".$item) : 0;
                        if($moderate != 0){
                            $info[$k]["moderate"] = $moderate;
                        }
                        $i++;
                    }elseif(strpos($item, "@,@") !== false){
                        $info[$k]["name"] = $k;
                        if($moderate != 0){
                            $info[$k]["moderate"] = $moderate;
                        }
                        $info[$k]["type"] = "array";
                        $info[$k]["value"] = $item;
                    }else{
                        $info[$k]["name"] = $k;
                        if($moderate != 0){
                            $info[$k]["moderate"] = $moderate;
                        }
                        $info[$k]["type"] = "string";
                        $info[$k]["value"] = $item;
                    }
                }
                $status = Response::HTTP_OK;
                $response = [
                    'status' => $status,
                    'data' => $info,
                ];
            }
        }else{
            try{
                $news = Info::where('id', $id)->firstOrFail();
                $status = Response::HTTP_OK;
                $response = [
                    'status' => $status,
                    'data' => $news,
                ];
            }catch (ModelNotFoundException $e){
                $status = Response::HTTP_BAD_REQUEST;
                $response = [
                    'status' => $status,
                    'message' => 'Ничего не найдено.',
                ];
            }catch (\Exception $e){
                $status = Response::HTTP_BAD_REQUEST;
                $response = [
                    'status' => $status,
                    'message' => 'Что-то пошло не так.',
                ];
            }
        }

        return $response;
    }

    /**
     * @param array|int $id
     * @return array|int
     */
    public static function destroy($id)
    {
        try {
            $delInfo = Info::findOrFail($id);
            $delInfo->delete();
            $status = Response::HTTP_OK;
            $response = [
                'status' => $status,
                'message' => 'Информация удалена.'
            ];
        }catch (ModelNotFoundException $e){
            $status = Response::HTTP_BAD_REQUEST;
            $response = [

app/Http/Controllers/Api/InfoController.php
<?php

namespace App\Http\Controllers\Api;

use App\Models\Info;
use App\Models\InfoModeration;
use App\Models\File;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Storage;

class InfoController extends Controller
{
    /**
     * InfoController constructor.
     */
    public function __construct()
    {
        Auth::loginUsingId(1);
    }

    /**]
     * @param Request $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function addInfo(Request $request){
        $data = $request->post();
        $response = Info::createOrUpdate($request, $data);
        return response()->json($response, $response['status']);
    }

    /**
     * @return \Illuminate\Http\JsonResponse
     */
    public function getInfo($id = ""){
        if($id == "infoform"){
            $id = "";
        }
        $response = Info::getInfo($id);
        return response()->json($response, $response['status']);
    }

    /**
     * @param $id
     * @return \Illuminate\Http\JsonResponse
     */
    public function destroy($id)
    {
        $response = Info::destroy($id);
        return response()->json($response, $response['status']);
    }

    public function acceptOrDeleteModeration(Request $request){
        $data = $request->all();
        $response = InfoModeration::acceptOrDelete($data);
        return response()->json($response, $response['status']);
    }
}

app/Http/Controllers/Dashboard/InfoController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Http\Requests\InfoCreationRequest;
use App\Models\Info;
use App\Models\PagLimit;
use Auth;
use Illuminate\Http\Request;

class InfoController extends Controller
{
    public function index(Request $request)
    {
        $limit = 10;
        $query = PagLimit::where('user_id', Auth::id())->first();
        if(!empty($query)) {
            $limit = $query->pag_limit;
        }
        $infos = Info::paginate($limit);
        return view('admin.infos.index', ['limit' => $limit])->with('infos', $infos);
    }

    public function create()
    {
        return view('admin.infos.create');
    }

    public function store(InfoCreationRequest $request)
    {
        $attributes = $request->only([
            'organisation_description',
            'stars',
            'payments_terms',
            'docs',
            'contraindications',
            'medical_profiles',
            'treatment_methods',
            'services',
        ]);

        $info = Info::create([
            'organisation_description' => $attributes['organisation_description'],
            'stars' => $attributes['stars'],
            'payments_terms' => $attributes['payments_terms'],
            'docs' => $attributes['docs'],
            'contraindications' => $attributes['contraindications'],
            'medical_profiles' => isset($attributes['medical_profiles']),
            'treatment_methods' => isset($attributes['treatment_methods']),
            'services' => $attributes['services'],
        ]);

        return redirect()->route('informations.show', ['id' => $info->id])->with('status', 'Успешно создана информация!');
    }

    /**
     * Display the specified resource.
     *
     * @param Info $info
     * @return \Illuminate\Http\Response
     * @throws AuthorizationException
     */
    public function show($id)
    {
        $info = Info::find(['id' => $id])->first();
        $this->authorize('object-read', \Auth::user());
        return view('admin.infos.show')->with('info', $info);
    }

    public function edit($id)
    {
        if ($info = Info::where('id', $id)->first()) {
            return view('admin.infos.edit')->with('info', $info);
        }
        return abort(404);
    }

    public function update($id, InfoCreationRequest $request)
    {
        $attributes = $request->only([
            'organisation_description',
            'stars',
            'payments_terms',
            'docs',
            'contraindications',
            'medical_profiles',
            'treatment_methods',
            'services',
        ]);

        $info = Info::where('id', $id)->update([
            'organisation_description' => $attributes['organisation_description'],
            'stars' => $attributes['stars'],
            'payments_terms' => $attributes['payments_terms'],
            'docs' => $attributes['docs'],
            'contraindications' => $attributes['contraindications'],
            'medical_profiles' => isset($attributes['medical_profiles']),
            'treatment_methods' => isset($attributes['treatment_methods']),
            'services' => $attributes['services'],
        ]);

        if ($info) {
            return redirect()->route('informations.show', ['id' => $id])->with('status', 'Успешно редактирована информация!');
        }
        return redirect()->route('informations.show', ['id' => $id])->with('status', 'failed');
    }

    public function destroy($id)
    {
        if (Info::where('id', $id)->delete()) {
            return back()->with(['status' => 'Информация успешно удалена']);
        }
        return back()->with(['status' => 'failed']);
    }
}

resources/views/admin/infos/create.blade.php
@extends('admin.layout.main')

@section('title', 'Создание новости')

@section('actions')
    <div class="links line-height-1">
        <a href="{{ route('informations.create') }}">Создать dummy post</a>
    </div>
@endsection

@section('content')

    @include('admin.parts.messages')
    <div class="row">
        <div class="col-lg-8">
            <div class="card">
                <div class="card-body">
                    <form action="{{ route('informations.store') }}" method="POST">
                        @csrf
                        <div class="row">
                            <div class="col-12 form-group">
                                <label for="organisation_description">Описание организации</label>
                                <textarea type="text" class="form-control" name="organisation_description" id="organisation_description" placeholder="Описание организации" rows="6"></textarea>
                                <span class="small">Внимание! Данная форма поддерживает markdown синтаксис. Используйте его.</span>
                            </div>

                            <div class="col-12 form-group">
                                <label for="stars">Звезды</label>
                                <input type="text" class="form-control" name="stars" id="stars" placeholder="Звезды">
                            </div>

                            <div class="col-12 form-group">
                                <label for="payments_terms">Условия оплаты</label>
                                <textarea type="text" class="form-control" name="payments_terms" id="payments_terms" placeholder="Условия оплаты" rows="6"></textarea>
                                <span class="small">Внимание! Данная форма поддерживает markdown синтаксис. Используйте его.</span>
                            </div>

                            <div class="col-12 form-group">
                                <label for="docs">Документация</label>
                                <textarea type="text" class="form-control" name="docs" id="docs" placeholder="Документация" rows="6"></textarea>
                                <span class="small">Внимание! Данная форма поддерживает markdown синтаксис. Используйте его.</span>
                            </div>

                            <div class="col-12 form-group">
                                <label for="contraindications">Противопоказания</label>
                                <textarea type="text" class="form-control" name="contraindications" id="contraindications" placeholder="Противопоказания" rows="6"></textarea>
                                <span class="small">Внимание! Данная форма поддерживает markdown синтаксис. Используйте его.</span>
                            </div>

                            <div class="col-12 form-group">
                                <label for="medical_profiles">Медицинские профили</label>
                                <input type="text" class="form-control" name="medical_profiles" id="medical_profiles" placeholder="Медицинские профили">
                            </div>

                            <div class="col-12 form-group">
                                <label for="treatment_methods">Методы лечения</label>
                                <input type="text" class="form-control" name="treatment_methods" id="treatment_methods" placeholder="Методы лечения">
                            </div>

                            <div class="col-12 form-group">
                                <label for="services">Сервисы</label>
                                <input type="text" class="form-control" name="services" id="services" placeholder="Сервисы">
                            </div>

                            <div class="col-12">
                                <button class="btn btn-primary">Создать информация</button>
                            </div>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/infos/edit.blade.php
@extends('admin.layout.main')

@section('title', 'Редактирование информации: ' . $info->id)

@section('content')

    @include('admin.parts.messages')
    <div class="row">
        <div class="col-lg-8">
            <div class="card">
                <div class="card-body">
                    <form action="{{ route('informations.update', ['id' => $info->id]) }}" method="POST">
                        <input name="_method" type="hidden" value="PUT">
                        @csrf
                        <div class="row">
                            <div class="col-12 form-group">
                                <label for="organisation_description">Описание организации</label>
                                <textarea type="text" class="form-control" name="organisation_description" id="organisation_description" placeholder="Описание организации" rows="6">{{ $info->organisation_description  }}</textarea>
                                <span class="small">Внимание! Данная форма поддерживает markdown синтаксис. Используйте его.</span>
                            </div>

                            <div class="col-12 form-group">
                                <label for="stars">Звезды</label>
                                <input type="text" class="form-control" name="stars" id="stars" placeholder="Звезды" value="{{ $info->stars }}">
                            </div>

                            <div class="col-12 form-group">
                                <label for="payments_terms">Условия оплаты</label>
                                <textarea type="text" class="form-control" name="payments_terms" id="payments_terms" placeholder="Условия оплаты" rows="6">{{ $info->payments_terms }}</textarea>
                                <span class="small">Внимание! Данная форма поддерживает markdown синтаксис. Используйте его.</span>
                            </div>

                            <div class="col-12 form-group">
                                <label for="docs">Документация</label>
                                <textarea type="text" class="form-control" name="docs" id="docs" placeholder="Документация" rows="6">{{ $info->docs }}</textarea>
                                <span class="small">Внимание! Данная форма поддерживает markdown синтаксис. Используйте его.</span>
                            </div>

                            <div class="col-12 form-group">
                                <label for="contraindications">Противопоказания</label>
                                <textarea type="text" class="form-control" name="contraindications" id="contraindications" placeholder="Противопоказания" rows="6">{{ $info->contraindications }}</textarea>
                                <span class="small">Внимание! Данная форма поддерживает markdown синтаксис. Используйте его.</span>
                            </div>

                            <div class="col-12 form-group">
                                <label for="medical_profiles">Медицинские профили</label>
                                <input type="text" class="form-control" name="medical_profiles" id="medical_profiles" placeholder="Медицинские профили" value="{{ $info->medical_profiles }}">
                            </div>

                            <div class="col-12 form-group">
                                <label for="treatment_methods">Методы лечения</label>
                                <input type="text" class="form-control" name="treatment_methods" id="treatment_methods" placeholder="Методы лечения" value="{{ $info->treatment_methods }}">
                            </div>

                            <div class="col-12 form-group">
                                <label for="services">Сервисы</label>
                                <input type="text" class="form-control" name="services" id="services" placeholder="Сервисы" value="{{ $info->services }}">
                            </div>

                            <div class="col-12">
                                <button class="btn btn-primary">Редактировать информация</button>
                            </div>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/infos/index.blade.php
@extends('admin.layout.main')

@section('title', 'Объекты')

@section('actions')
    <div class="links line-height-1">
        {{--@can('object-create')--}}
            <a href="{{ route('informations.create') }}">Создать</a>
        {{--@endcan--}}
    </div>
@endsection

@section('content')

    @include('admin.parts.messages')
    <div class="row row-cards row-desk">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <div class="card-title">Список объектов</div>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-striped">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>Описание организации</th>
                                <th>Создан</th>
                                <th>Обновлен</th>
                                <th>Звезды</th>
                                {{--<th>Активен?</th>--}}
                                <th>Действия</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($infos as $info)
                                <tr>
                                    <td class="w-1">{{ $info->id }}</td>
                                    <td><a href="{{ route('informations.edit', ['id' => $info->id]) }}">{!! $info->organisation_description !!}</a></td>
                                    <td>{{ $info->created_at->format('m/d/Y') }}</td>
                                    <td>{{ $info->updated_at->format('m/d/Y') }}</td>
                                    <td><span class="tag tag-green">{{ $info->stars }}</span></td>
                                    <td class="form-inline">
                                        <a href="{{ route('informations.edit', ['id' => $info->id]) }}" class="btn btn-sm btn-primary d-inline-block mr-1">Изменить</a>
                                        <form action="{{ route('informations.destroy', ['id' => $info->id]) }}" method="POST" class="d-inline-block">
                                            @method('DELETE')
                                            @csrf
                                            <button class="btn btn-sm btn-outline-danger">Удалить</button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="card-footer">
                    {{ $infos->links() }}
                    <form class="pagination-limit" action="/pagination_limit" method="POST">
                        @csrf
                        <input type="text" name='pag_limit' class="form-control-sm" value="{{$limit}}" />
                        <input type="submit" class="btn btn-primary btn-sm" id="p-limit" value="Limit">
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/infos/show.blade.php
@extends('admin.layout.main')

@section('title', 'Просмотр информации')

@section('content')
    @include('admin.parts.messages')

    <div class="row">
        <div class="col-lg-7">
            <div class="card position-relative">
                <div class="card-body">
                    <div class="text-muted">
                        Описание организации:
                        {!! $info->organisation_description !!}
                    </div>

                    <div class="text-muted">
                        Условия оплаты:
                        {!! $info->payments_terms !!}
                    </div>

                    <div class="text-muted">
                        Документация:
                        {!! $info->docs !!}
                    </div>

                    <div class="text-muted">
                        Противопоказания:
                        {!! $info->contraindications !!}
                    </div>

                    <div class="text-muted">
                        Звезды: {{ $info->stars }}
                    </div>

                    <div class="text-muted">
                        Медицинские профили:
                        {{ $info->payments_terms }}
                    </div>

                    <div class="text-muted">
                        Методы лечения:
                        {{ $info->treatment_methods }}
                    </div>

                    <div class="text-muted">
                        Сервисы:
                        {{ $info->services }}
                    </div>

                    <div class="text-muted">
                        Создан:
                        {{ $info->created_at }}
                    </div>

                    <div class="text-muted">
                        Обновлен:
                        {{ $info->updated_at }}
                    </div>
                </div>
                @canany(['info-update', 'info-delete'])
                    <div class="card-actions">
                        @can('info-update')
                            <a href="{{ route('info.edit', ['id' => $info->id]) }}"><i class="fa fa-pen"></i></a>
                        @endcan
                        @can('info-delete')
                            <form action="{{ route('info.destroy', ['id' => $info->id]) }}" method="POST" class="d-inline ml-2">
                                @csrf
                                @method('delete')
                                <button class="fa fa-times btn-unstyled"></button>
                            </form>
                        @endcan
                    </div>
                @endcanany
            </div>
        </div>
    </div>
@endsection