routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::middleware(['auth'])->namespace('Dashboard')->group(function () {
    Route::get('/', 'IndexController@index')->name('admin.index');
    Route::resource('news', 'NewsController');
    Route::resource('roles', 'RoleController');
    Route::resource('users', 'UserController')->except(['show']);
    Route::resource('deseases', 'DeseaseController');
    Route::resource('objects', 'ObjectController')->only(['index', 'create', 'edit', 'store', 'update', 'destroy']);
    Route::post('pagination_limit', 'ObjectController@changePaginationLimit');
    Route::resource('faqs', 'FaqController')->only(['index', 'edit', 'create', 'store', 'update', 'destroy']);
    Route::resource('tags', 'TagController')->only(['index', 'store', 'update', 'destroy']);
    Route::get('search{page?}', 'ObjectController@search');
    Route::resource('locations', 'LocationController');
    Route::resource('informations', 'InfoController');
    Route::resource('forms', 'CardsController');
    Route::resource('galleries', 'GalleryController');
});

app/Models/Tag.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Tag extends Model
{
    protected $guarded = [];
    public function faqs()
    {
        return $this->belongsToMany(Faq::class);
    }

    public function page()
    {
        return $this->belongsTo(Page::class);
    }
}

app/Http/Controllers/Dashboard/TagController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Models\Tag;
use Illuminate\Http\Request;

class TagController extends Controller
{
    public function index()
    {
        return view('admin.tags.index')->with('tags', Tag::paginate(20));
    }

    public function store(Request $request)
    {
        $this->validate($request, ['slug' => 'required|unique:tags,slug', 'name' => 'required|string']);
        $tag = Tag::create($request->only(['slug', 'name']));
        return redirect()->back();
    }

    public function destroy(Tag $tag)
    {
        $tag->delete();
        return redirect()->back();
    }
}

resources/views/admin/tags/index.blade.php
@extends('admin.layout.main')

@section('title', 'Теги')

@section('content')
    @include('admin.parts.messages')
    <div class="row row-cards row-desk">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                    <div class="card-title">Список тегов</div>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-striped">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>Название</th>
                                <th>Slug</th>
                                <th>Кол-во записей</th>
                                <th>Действие</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($tags as $tag)
                                <tr>
                                    <td class="w-1">{{ $tag->id }}</td>
                                    <td>{{ $tag->name }}</td>
                                    <td>{{ $tag->slug }}</td>
                                    <td>{{ $tag->faqs()->count() }}</td>
                                    <td>
                                        <form action="{{ route('tags.destroy', ['id' => $tag->id]) }}" method="POST">
                                            @method('DELETE')
                                            @csrf
                                            <button class="btn btn-sm btn-outline-danger">Удалить</button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="card-footer">
                    {{ $tags->links() }}
                </div>
            </div>
        </div>
        {{--@can('tag-create')--}}
            <div class="col-md-4">
                <div class="card">
                    <div class="card-header">
                        <div class="card-title">Создание тега</div>
                    </div>
                    <div class="card-body">
                        <form action="{{ route('tags.store') }}" method="POST">
                            @csrf
                            <div class="form-group">
                                <label for="name">Имя</label>
                                <input type="text" name="name" id="name" placeholder="отдых" class="form-control">
                            </div>
                            <div class="form-group">
                                <label for="slug">Уникальный идентификатор</label>
                                <input type="text" name="slug" id="slug" placeholder="rest" class="form-control">
                            </div>
                            <button class="btn btn-primary">Создать</button>
                        </form>
                    </div>
                </div>
            </div>
        {{--@endcan--}}
    </div>
@endsection