routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::middleware(['auth'])->namespace('Dashboard')->group(function () {
    Route::get('/', 'IndexController@index')->name('admin.index');
    Route::resource('news', 'NewsController');
    Route::resource('roles', 'RoleController');
    Route::resource('users', 'UserController')->except(['show']);
    Route::resource('deseases', 'DeseaseController');
    Route::resource('objects', 'ObjectController')->only(['index', 'create', 'edit', 'store', 'update', 'destroy']);
    Route::post('pagination_limit', 'ObjectController@changePaginationLimit');
    Route::resource('faqs', 'FaqController')->only(['index', 'edit', 'create', 'store', 'update', 'destroy']);
    Route::resource('tags', 'TagController')->only(['index', 'store', 'update', 'destroy']);
    Route::get('search{page?}', 'ObjectController@search');
    Route::resource('locations', 'LocationController');
    Route::resource('informations', 'InfoController');
    Route::resource('forms', 'CardsController');
    Route::resource('galleries', 'GalleryController');
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Laravel\Passport\HasApiTokens;

class User extends Authenticatable
{
    use Notifiable, HasApiTokens;

    protected $permissionsList;

    //public $appends = ['image'];

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'father_name',
        'last_name',
        'city',
        'role_id'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    public function role()
    {
        return $this->belongsTo(Role::class)->with('permissions');
    }

    public function permissions()
    {
        if (!$this->permissionsList) {
            $this->permissionsList = $this->role ? $this->role->permissions : Permission::where('has_default',
                true)->get();
        }

        return $this->permissionsList;
    }

    public function hasPermission(string $permission)
    {
        return $this->permissions()->where('slug', $permission)->count();
    }

    /*public function getImageAttribute()
    {
        $url = $this->avatar_url ?? 'public/images/avatar.svg';
        return \Storage::url($url);
    }*/

    /*public function getAvatarUrlAttribute($avatar)
    {
        return \Storage::url($avatar);
    }*/
}

app/Http/Controllers/Api/UserController.php
<?php

namespace App\Http\Controllers\Api;

use App\Models\File;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Storage;

class UserController extends Controller
{
    public function update(Request $request)
    {
        $errors = [];
        $user = auth()->guard('api')->user();
        $this->validate($request, [
            'profileform' => 'required|array',
            'profileform.avatar' => 'required',
            'profileform.name.value' => 'required|string',
            'profileform.surename.value' => 'required|string',
            'profileform.fathername.value' => 'required|string',
            'profileform.oldpassword' => 'required|array',
            'profileform.password' => 'required|array',
        ], [
            "profileform.name.value.required" => "Поле Имя обязательное для заполнения.",
            'profileform.surename.value.required' => "Поле Фамилия обязательное для заполнения.",
            'profileform.fathername.value.required' => "Поле Отчество обязательное для заполнения.",
            'profileform.oldpassword.required' => "Поле текущий пароль обязательное для заполнения.",
            'profileform.password.required' => "Поле новый пароль обязательное для заполнения.",
        ]);

        $user->name = $request->input('profileform.name.value');
        $user->last_name = $request->input('profileform.surename.value');
        $user->father_name = $request->input('profileform.fathername.value');
        if ($request->input('profileform.avatar.value.0') != null) {
            if ($request->input('profileform.avatar.value.0.size')) {
                $imgInfo = $request->input('profileform.avatar.value.0.url');
                $imgInfo = str_replace('data:image/jpeg;base64,','',$imgInfo);
                $imgInfo = str_replace('data:image/jpg;base64,','',$imgInfo);
                $imgInfo = str_replace('data:image/png;base64,','',$imgInfo);
                $imgInfo = str_replace('data:image/bmp;base64,','',$imgInfo);
                $img = explode(',', $imgInfo);
                $ini = substr($img[0], 11);
                $type = explode(';', $ini);
                $filename = $user->id.'.png';

                if(Storage::disk('avatars')->put($filename, base64_decode($imgInfo))){
                    $user->avatar_url = $filename;
                }else{
                    return response()->json(["message" => "Write error.",
                        "errors" => ["profileform.avatar.value" => ["Disk write error "]]], 422);
                }
            }
        }
        if(!empty($request->input('profileform.password.value')) || !empty($request->input('profileform.oldpassword.value'))){
            if(strlen($request->input('profileform.password.value')) < 8){
                return response()->json(["message" => "The given data was invalid.",
                    "errors" => ["profileform.password.value" => ["Текущий пароль должен быть не менее 8 символов"]]], 422);
            }
            if(strlen($request->input('profileform.oldpassword.value')) < 8){
                return response()->json(["message" => "The given data was invalid.",
                    "errors" => ["profileform.oldpassword.value" => ["Новый пароль должен быть не менее 8 символов"]]], 422);
            }
            if($request->input('profileform.password.value') == ""){
                return response()->json(["message" => "The given data was invalid.",
                    "errors" => ["profileform.password.value" => ["Не заполнен новый пароль"]]], 422);
            }elseif($request->input('profileform.oldpassword.value') == ""){
                return response()->json(["message" => "The given data was invalid.",
                    "errors" => ["profileform.oldpassword.value" => ["Не заполнен текущий пароль"]]], 412);
            } else {
                if (Hash::check($request->input('profileform.oldpassword.value'), $user->password)) {
                    $user->password = Hash::make($request->input('profileform.password.value'));
                } else {
                    return response()->json(["message" => "The given data was invalid.",
                        "errors" => ["profileform.oldpassword.value" => ["Введен неверный текущий пароль"]]], 412);
                }
            }
        }

        $user->save();
        return response()->json(['success' => true, 'user' => $user]);
    }

    public function me()
    {
        return response()->json(auth()->user());
    }
}

app/Http/Controllers/Dashboard/UserController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Requests\UserUpdateRequest;
use App\Models\Role;
use App\Models\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class UserController extends Controller
{
    public function index()
    {
        $this->authorize('user-read', \Auth::user());

        $users = User::paginate(20);

        return view('admin.user.index')->with('users', $users);
    }

    public function edit(User $user)
    {
        $this->authorize('user-update', \Auth::user());
        $roles = Role::all();
        return view('admin.user.edit')
            ->with('user', $user)
            ->with('roles', $roles);
    }

    public function update(UserUpdateRequest $request, User $user)
    {
        $this->authorize('user-update', \Auth::user());
        $user->update($request->all());
        return redirect()->route('users.index')->with('status', 'Успешно обновлен пользователь #' . $user->id);
    }

    public function destroy(User $user)
    {
        $this->authorize('user-delete', \Auth::user());
        $user->delete();

        return redirect()->route('users.index')->with('status', 'Успешно удален пользователь #' . $user->id);
    }
}

resources/views/admin/user/edit.blade.php
@extends('admin.layout.main')

@section('title', 'Пользователи')

@section('content')
    @include('admin.parts.messages')

    <div class="row row-cards row-desk">
        <div class="col-md-6">
            <form method="POST" action="{{ route('users.update', ['id' => $user->id]) }}" class="card">
                @csrf
                @method('PUT')
                <div class="card-header">
                    <div class="card-title">Редактирование пользователя {{ $user->name }}</div>
                </div>
                <div class="card-body">
                    <div class="form-group">
                        <label for="email">Электронная почта</label>
                        <input type="text" name="email" id="email" class="form-control" placeholder="Email" value="{{ $user->email }}">
                    </div>
                    <div class="form-group">
                        <label for="name">Имя пользователя</label>
                        <input type="text" name="name" id="name" class="form-control" placeholder="Имя пользователя" value="{{ $user->name }}">
                    </div>
                    <div class="form-group">
                        <label for="last_name">Фамилия пользователя</label>
                        <input type="text" name="last_name" id="last_name" class="form-control" placeholder="Фамилия пользователя" value="{{ $user->last_name }}">
                    </div>

                    <div class="form-group">
                        <label for="father_name">Отчество пользователя</label>
                        <input type="text" name="father_name" id="father_name" class="form-control" placeholder="Отчество пользователя" value="{{ $user->father_name }}">
                    </div>

                    <div class="form-group">
                        <label for="role_id">Роль</label>
                        <select name="role_id" id="role_id" class="custom-select form-control">
                            <option value="">Без роли</option>
                            @foreach($roles as $role)
                                <option value="{{ $role->id }}"
                                    {{ $user->role_id == $role->id ? 'selected' : '' }}
                                >{{ $role->name }}</option>
                            @endforeach
                        </select>
                    </div>
                </div>
                <div class="card-footer">
                    <button class="btn btn-primary">Обновить</button>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/admin/user/index.blade.php
@extends('admin.layout.main')

@section('title', 'Пользователи')

@section('content')
    @include('admin.parts.messages')

    <div class="row">
        <div class="col-12">
            <div class="card position-relative">
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table card-table table-striped table-vcenter">
                            <thead>
                                <tr>
                                    <th colspan="2">Пользователь</th>
                                    <th>Email</th>
                                    <th>Дата регистрации</th>
                                    <th>Действия</th>
                                </tr>
                            </thead>
                            <tbody>
                            @foreach($users as $user)
                            <tr>
                                <td class="w-1">
                                    <span class="avatar avatar-white" style="background-image: url('{{ $user->image }}')"></span>
                                </td>
                                <td>
                                    {{ $user->name }}
                                </td>
                                <td>
                                    {{ $user->email }}
                                </td>
                                <td>
                                    {{ $user->created_at }}
                                </td>
                                <td class="w-1">
                                    @can('user-update')
                                        <a href="{{ route('users.edit', ['id' => $user->id]) }}" class="icon mr-2"><i class="fa fa-pen"></i></a>
                                    @endcan
                                    @can('user-delete')
                                        <form action="{{ route('users.destroy', ['id' => $user->id]) }}" method="POST" class="d-inline">
                                            @csrf
                                            @method('DELETE')
                                            <button class="icon btn-unstyled"><i class="fa fa-trash"></i></button>
                                        </form>
                                    @endcan
                                </td>
                            </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="card-footer">
                    {{ $users->links() }}
                </div>
            </div>
        </div>
    </div>
@endsection