routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::middleware(['auth'])->namespace('Dashboard')->group(function () {
    Route::get('/', 'IndexController@index')->name('admin.index');
    Route::resource('news', 'NewsController');
    Route::resource('roles', 'RoleController');
    Route::resource('users', 'UserController')->except(['show']);
    Route::resource('deseases', 'DeseaseController');
    Route::resource('objects', 'ObjectController')->only(['index', 'create', 'edit', 'store', 'update', 'destroy']);
    Route::post('pagination_limit', 'ObjectController@changePaginationLimit');
    Route::resource('faqs', 'FaqController')->only(['index', 'edit', 'create', 'store', 'update', 'destroy']);
    Route::resource('tags', 'TagController')->only(['index', 'store', 'update', 'destroy']);
    Route::get('search{page?}', 'ObjectController@search');
    Route::resource('locations', 'LocationController');
    Route::resource('informations', 'InfoController');
    Route::resource('forms', 'CardsController');
    Route::resource('galleries', 'GalleryController');
});

resources/views/admin/layout/parts/footer.blade.php
<div class="footer">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-auto">
                <div class="row align-items-center">
                    <div class="col-auto">
                        <ul class="list-inline list-inline-dots mb-0">
                            <li class="list-inline-item"><a href="#">Документация</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

resources/views/admin/layout/parts/header.blade.php
<div class="d-flex">
    <a class="header-brand" href="/">
        Zdravproduct<span class="text-primary">Admin</span>
    </a>
    <div class="d-flex order-lg-2 ml-auto">
        {{--<div class="dropdown d-none d-md-flex">--}}
        {{--<a class="nav-link icon" data-toggle="dropdown">--}}
        {{--<i class="fe fe-bell"></i>--}}
        {{--<span class="nav-unread"></span>--}}
        {{--</a>--}}
        {{--<div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow">--}}
        {{--<a href="#" class="dropdown-item d-flex">--}}
        {{--<span class="avatar mr-3 align-self-center" style="background-image: url(demo/faces/male/41.jpg)"></span>--}}
        {{--<div>--}}
        {{--<strong>Nathan</strong> pushed new commit: Fix page load performance issue.--}}
        {{--<div class="small text-muted">10 minutes ago</div>--}}
        {{--</div>--}}
        {{--</a>--}}
        {{--<a href="#" class="dropdown-item d-flex">--}}
        {{--<span class="avatar mr-3 align-self-center" style="background-image: url(demo/faces/female/1.jpg)"></span>--}}
        {{--<div>--}}
        {{--<strong>Alice</strong> started new task: Tabler UI design.--}}
        {{--<div class="small text-muted">1 hour ago</div>--}}
        {{--</div>--}}
        {{--</a>--}}
        {{--<a href="#" class="dropdown-item d-flex">--}}
        {{--<span class="avatar mr-3 align-self-center" style="background-image: url(demo/faces/female/18.jpg)"></span>--}}
        {{--<div>--}}
        {{--<strong>Rose</strong> deployed new version of NodeJS REST Api V3--}}
        {{--<div class="small text-muted">2 hours ago</div>--}}
        {{--</div>--}}
        {{--</a>--}}
        {{--<div class="dropdown-divider"></div>--}}
        {{--<a href="#" class="dropdown-item text-center text-muted-dark">Mark all as read</a>--}}
        {{--</div>--}}
        {{--</div>--}}
        <div class="dropdown">
            <a href="#" class="nav-link pr-0 leading-none" data-toggle="dropdown">
                <span class="avatar avatar-white" style="background-image: url('{{ $currentUser->image }}')"></span>
                <span class="ml-2 d-none d-lg-block">
                      <span class="text-default">{{ $currentUser->name }}</span>
                      <small class="text-muted d-block mt-1">{{ $currentUser->role ? $currentUser->role->name : '' }}</small>
                </span>
            </a>
            <div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow">
                <a class="dropdown-item" href="#">
                    <i class="dropdown-icon fe fe-user"></i> Профиль
                </a>
                <div class="dropdown-divider"></div>
                <form action="{{route('logout')}}" method="POST">
                    {{ csrf_field() }}
                    <button class="dropdown-item" type="submit">
                        <i class="dropdown-icon fe fe-log-out"></i> Выйти
                    </button>
                </form>
            </div>
        </div>
    </div>
    <a href="#" class="header-toggler d-lg-none ml-3 ml-lg-0" data-toggle="collapse" data-target="#headerMenuCollapse">
        <span class="header-toggler-icon"></span>
    </a>
</div>

resources/views/admin/layout/parts/menu.blade.php
<li class="nav-item">
    <a href="{{ route('admin.index') }}" class="nav-link {{ request()->is('/') ? 'active' : '' }}"><i class="fe fe-home"></i> Главная</a>
</li>
@can('news-read')
<li class="nav-item">
    <a href="{{ route('news.index') }}" class="nav-link {{ request()->is('news') ? 'active' : '' }}"><i class="fe fe-file"></i> Новости</a>
</li>
@endcan
@can('role-read')
<li class="nav-item">
    <a href="{{ route('roles.index') }}" class="nav-link {{ request()->is('roles') ? 'active' : '' }}"><i class="fe fe-users"></i> Роли</a>
</li>
@endcan
@can('user-read')
<li class="nav-item">
    <a href="{{ route('users.index') }}" class="nav-link {{ request()->is('users') ? 'active' : '' }}"><i class="fe fe-user"></i> Пользователи</a>
</li>
@endcan
<li class="nav-item">
    <a href="{{ route('objects.index') }}" class="nav-link {{ request()->is('objects') ? 'active' : '' }}"><i class="fe fe-user"></i> Объекты</a>
</li>
<li class="nav-item">
    <a href="{{ route('faqs.index') }}" class="nav-link {{ request()->is('faqs') ? 'active' : '' }}"><i class="fe fe-list"></i> Faqs</a>
</li>
<li class="nav-item">
    <a href="{{ route('tags.index') }}" class="nav-link {{ request()->is('tags') ? 'active' : '' }}"><i class="fe fe-hash"></i> Теги</a>
</li>
<li class="nav-item">
    <a href="{{ route('locations.index') }}" class="nav-link {{ request()->is('locations') ? 'active' : '' }}"><i class="fe fe-user"></i> Локации</a>
</li>
<li class="nav-item">
    <a href="{{ route('informations.index') }}" class="nav-link {{ request()->is('informations') ? 'active' : '' }}"><i class="fe fe-user"></i> Информации</a>
</li>
<li class="nav-item">
    <a href="{{ route('forms.index') }}" class="nav-link {{ request()->is('forms') ? 'active' : '' }}"><i class="fe fe-list"></i> Анкеты</a>
</li>
<li class="nav-item">
    <a href="{{ route('galleries.index') }}" class="nav-link {{ request()->is('galleries') ? 'active' : '' }}"><i class="fe fe-list"></i> Галерея</a>
</li>